[build]
target = ["armv7-unknown-linux-gnueabihf","x86_64-unknown-linux-gnu"]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.x86_64-unknown-linux-gnu]
linker = "cc"

[target.riscv64gc-unknown-linux-musl]
# binutils 2.42 已支持新扩展，无需禁用
linker = "riscv64-unknown-linux-musl-gcc"
