[build]
target = ["aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-unknown-linux-gnu]
linker = "cc"

[target.riscv64gc-unknown-linux-musl]
# binutils 2.42 已支持新扩展，无需禁用
linker = "riscv64-unknown-linux-musl-gcc"
